name: Update README with Real-time Stats

on:
  # Update every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Run on push to main
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update README with latest activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: 'Update README with latest activity'
          MAX_LINES: 5